version: '3.8'

services:
  app:
    build: .
    container_name: jonathancarvalho039/api-order-hub:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
