spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: order-hub
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/order_hub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          show_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SERCRET:orderhub}
  expiration-hour: ${EXPIRATION_TOKEN:168}

server:
  error:
    include-message: always  # Incluir mensagens nos erros
    include-binding-errors: always  # Incluir erros de binding na resposta


aws:
  access-key: "AKIA5J4"
  secret-key: "5J4"
  region: "us-east-2"
  endpoint: https://image-order-hub.s3.amazonaws.com
  bucket: image-order-hub

