spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: order-hub
  datasource:
    url: ${URL_DATABASE:jdbc:sqlserver://servidor-orderhub.database.windows.net:1433;databaseName=bd-projeto-orderhub}
    username: ${USER_NAME:admin-orderhub}
    password: ${PASSWORD:Order123@}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SERCRET:orderhub}
  expiration-hour: ${EXPIRATION_TOKEN:168}

server:
  error:
    include-message: always  # Incluir mensagens nos erros
    include-binding-errors: always  # Incluir erros de binding na resposta


aws:
  bucket:
    access-key: ${AWS_ACCESS_KEY_ID:5J4}
    secret-key: ${AWS_SECRET_ACCESS_KEY:5J4}
    region: ${AWS_REGION:us-east-1}
    endpoint: https://image-order-hub.s3.amazonaws.com
    bucket: image-order-hub

  sqs:
    region: ${AWS_REGION:us-east-1}
    endpoint: ""
    access-key-id: ${AWS_ACCESS_KEY_ID:test}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:test}

queue:
  order:
    name: ${QUEUE_NAME:notification-orderhub}

