spring:
  datasource:
    url: jdbc:mysql://order-hub-db.cy356uxitvhj.us-east-1.rds.amazonaws.com:3306/order_hub?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=SERVER&socketTimeout=30000&connectTimeout=10000&autoReconnect=true
    username: orderhub
    password: orderhub
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      initialization-fail-timeout: 10000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate # Alterado de update para validate em produção
      properties:
        hibernate:
          connection.provider_disables_autocommit: true
          format_sql: true
          show_sql: true
          jdbc:
            time_zone: SERVER
    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none