spring:
  application:
    name: order-hub

  # Configuração do banco de dados MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/orderhub
    username: root
    password: 180118
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

  # Configuração de e-mail
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: orderhub059@gmail.com
#    password: gysr rbmv uubw rvif
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    default-encoding: UTF-8

# Configuração do servidor
server:
  address: 0.0.0.0




