server:
  port: 8080
  address: 0.0.0.0
  error:
    include-message: always  # Incluir mensagens nos erros
    include-binding-errors: always  # Incluir erros de binding na resposta

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: order-hub
  datasource:
    url: ${DATA_BASE_URL}
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SMTP:orderhub059@gmail.com}
    password: ${PASSWORD_SMTP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

jwt:
  secret: ${JWT_SECRET:orderhub}  # Corrigi o nome da variável para JWT_SECRET
  expiration-hour: ${EXPIRATION_TOKEN:168}

aws:
  bucket:
    endpoint: https://image-order-hub.s3.amazonaws.com
    bucket: ordehub-image

  region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:AKIA3FRRJEMNRYCSBOW3}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}

