spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: order-hub
  datasource:
    url: ${URL_DATABASE:jdbc:sqlserver://servidor-orderhub.database.windows.net:1433;databaseName=bd-projeto-orderhub}
    username: ${USER_NAME:admin-orderhub}
    password: ${PASSWORD:Order123@}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SERCRET:orderhub}
  expiration-hour: ${EXPIRATION_TOKEN:168}

logging:
  level:
    org:
      springframework:
        security: DEBUG  # Para depuração de segurança
        org.springframework.web: DEBUG  # Para depuração das requisições web
    hibernate:
      SQL: DEBUG  # Para logar as queries SQL executadas pelo Hibernate
      type:
        descriptor:
          sql: TRACE  # Para logar detalhes dos parâmetros da query
    root: INFO  # Define o nível de log global (pode ser DEBUG ou INFO, dependendo do seu caso)

  # Definindo os padrões de log mais detalhados
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Personalizando o formato dos logs no console
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Personalizando o formato dos logs nos arquivos

server:
  error:
    include-message: always  # Incluir mensagens nos erros
    include-binding-errors: always  # Incluir erros de binding na resposta


aws:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  region: "us-east-2"
  endpoint: https://image-order-hub.s3.amazonaws.com
  bucket: image-order-hub

