spring:
  application:
    name: order-hub

  # TODO: Change to MySQL for pre-production
  datasource:
    url: jdbc:mysql://localhost:3307/orderhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: orderhub
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  # TODO: Change to H2 for testing
  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:mem:teste
  #   username: sa
  #   password:
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  # jpa:
  #   hibernate:
  #     ddl-auto: create
  #   show-sql: true
  #   database-platform: org.hibernate.dialect.H2Dialect
  # server:
  #   error:
  #     include-message: always
  #     include-binding-errors: always
  # jpa:
  #   defer-datasource-initialization: true

# origins:
#   url: http://localhost:5173
