server:
  port: 8080
  address: 0.0.0.0
  error:
    include-message: always  # Incluir mensagens nos erros
    include-binding-errors: always  # Incluir erros de binding na resposta

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: order-hub
  datasource:
    url: ${DATA_BASE_URL}
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SECRET:orderhub}  # Corrigi o nome da variável para JWT_SECRET
  expiration-hour: ${EXPIRATION_TOKEN:168}

aws:
  bucket:
    access-key: ${AWS_ACCESS_KEY_ID:5J4}
    secret-key: ${AWS_SECRET_ACCESS_KEY:5J4}
    region: ${AWS_REGION:us-east-1}
    endpoint: https://image-order-hub.s3.amazonaws.com
    bucket: image-order-hub

  sqs:
    region: ${AWS_REGION:us-east-1}
    endpoint: ""
    access-key-id: ${AWS_ACCESS_KEY_ID:ASIAVGZ6ASQ4VBNUJVSZ}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:k6oyUMIpnuQgq6xOZcgUs2h2ykpgBgcexqDQMJOG}
    session-token: ${AWS_SESSION_TOKEN}

queue:
  order:
    name: ${QUEUE_NAME:notification-orderhub}
