server:
  port: 8080
  address: 0.0.0.0
  error:
    include-message: always  # Incluir mensagens nos erros
    include-binding-errors: always  # Incluir erros de binding na resposta

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: order-hub
  datasource:
    url: jdbc:mysql://order-hub-db.cy356uxitvhj.us-east-1.rds.amazonaws.com:3306/order_hub?allowPublicKeyRetrieval=true&sslMode=DISABLED&serverTimezone=UTC
    username: orderhub
    password: orderhub
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          show_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SECRET:orderhub}  # Corrigi o nome da variável para JWT_SECRET
  expiration-hour: ${EXPIRATION_TOKEN:168}

aws:
  access-key: "AKIA5J4"
  secret-key: "5J4"
  region: "us-east-2"
  endpoint: https://image-order-hub.s3.amazonaws.com
  bucket: image-order-hub
