name: Deploy Java Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RDS_ENDPOINT: order-hub-db.cy356uxitvhj.us-east-1.rds.amazonaws.com
  SPRING_PROFILES_ACTIVE: prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          PRIVATE_IP: ${{ secrets.EC2_PRIVATE_IP }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Copia o JAR e application-prod.properties
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            target/your-app.jar \
            ubuntu@$PUBLIC_IP:/tmp/
          
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            src/main/resources/application-prod.properties \
            ubuntu@$PUBLIC_IP:/tmp/
          
          # Comandos na instância privada via pública
          ssh -i ~/.ssh/id_rsa ubuntu@$PUBLIC_IP << 'EOF'
            ssh -i /home/ubuntu/orderhub.pem ubuntu@$PRIVATE_IP << 'ENDSSH'
              mkdir -p ~/app
              mv /tmp/your-app.jar ~/app/
              mv /tmp/application-prod.properties ~/app/
          
              # Configura variáveis para Java/Spring
              export SPRING_DATASOURCE_URL="jdbc:mysql://$RDS_ENDPOINT:3306/orderhub"
              export SPRING_DATASOURCE_USERNAME="$DB_USERNAME"
              export SPRING_DATASOURCE_PASSWORD="$DB_PASSWORD"
          
              # Reinicia o serviço
              sudo systemctl restart your-java-app.service
            ENDSSH
          EOF