name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Compile Java Application
        run: mvn clean compile

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Run Tests
        run: mvn test

  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t jonathancarvalho039/api-order-hub:latest .

      - name: Push Docker Image
        run: docker push jonathancarvalho039/api-order-hub:latest

  deploy-a:
    name: Deploy instace-a
    runs-on: [self-hosted, instace-a]
    needs: push

    steps:
      - name: Pull latest image and restart container
        run: |
          sudo docker stop back-end || true
          sudo docker rm back-end || true
          sudo docker rmi jonathancarvalho039/api-order-hub || true
          sudo docker pull jonathancarvalho039/api-order-hub
          sudo docker run --name back-end -d -p 8080:8080 \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e PASSWORD_SMTP="${{secrets.PASSWORD_SMTP}}" \
            -e MAIL_SMTP=orderhub059@gmail.com \
            -e AWS_REGION=us-east-1 \
            -e QUEUE_NAME=notification-orderhub \
            -e DATA_BASE_URL="jdbc:mysql://order-hub-db.cy356uxitvhj.us-east-1.rds.amazonaws.com:3306/order_hub?allowPublicKeyRetrieval=true&sslMode=DISABLED&serverTimezone=UTC" \
            -e DATA_BASE_USERNAME=orderhub \
            -e DATA_BASE_PASSWORD=orderhub \
            jonathancarvalho039/api-order-hub

  deploy-b:
    name: Deploy instace-b
    runs-on: [self-hosted, instace-b]
    needs: push

    steps:
      - name: Pull latest image and restart container
        run: |
          sudo docker stop back-end || true
          sudo docker rm back-end || true
          sudo docker rmi jonathancarvalho039/api-order-hub || true
          sudo docker pull jonathancarvalho039/api-order-hub
          sudo docker run --name back-end -d -p 8080:8080 \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e PASSWORD_SMTP="${{secrets.PASSWORD_SMTP}}" \
            -e MAIL_SMTP=orderhub059@gmail.com \
            -e AWS_REGION=us-east-1 \
            -e QUEUE_NAME=notification-orderhub \
            -e DATA_BASE_URL="jdbc:mysql://order-hub-db.cy356uxitvhj.us-east-1.rds.amazonaws.com:3306/order_hub?allowPublicKeyRetrieval=true&sslMode=DISABLED&serverTimezone=UTC" \
            -e DATA_BASE_USERNAME=orderhub \
            -e DATA_BASE_PASSWORD=orderhub \
            jonathancarvalho039/api-order-hub
